train_dataset:
  type: Cityscapes
  dataset_root: datasets/cityscapes
  transforms:
    - type: ResizeStepScaling
      min_scale_factor: 0.5
      max_scale_factor: 2.0
      scale_step_size: 0.25
    - type: RandomPaddingCrop
      crop_size: [1024, 512]
    - type: RandomHorizontalFlip
    - type: RandomDistort
      brightness_range: 0.4
      contrast_range: 0.4
      saturation_range: 0.4
    - type: Normalize
  mode: train

val_dataset:
  type: Cityscapes
  dataset_root: datasets/cityscapes
  transforms:
    - type: Normalize
  mode: val

model:
  type: ENet
  backbone:
    type: ENETV1
    num_classes: 19
  num_classes: 19
  pretrained: Null

optimizer:
  type: adam
  weight_decay: 0.0002

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.001
  end_lr: 0
  power: 0.9

iters: 120000
batch_size: 8

loss:
  types:
    - type: CrossEntropyLoss
  coef: [1]
